apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yrh3itwq1-go 
  janus-idp.io/tekton: yrh3itwq1-go
  backstage.io/kubernetes-id: yrh3itwq1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yrh3itwq1-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  