apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yrh3itwq1-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-954dab5336.6sji.p3.openshiftapps.com/rhtap/rhtap-qe:0b994a80cb1df84fd9d201f50c5fe98422351f03@sha256:1b4de5ccada634821bc58a5e5acfb811a983ea1f8241f7db16f47a853457b1ab
          name: container-image
